version: '3.8'

services:
  nginx-service:
    container_name: my-dynamic-web-server
    build:
      context: ./nginx-web
    ports:
      - "8080:80"
    environment:
      - S3_BUCKET_NAME=my-dynamic-website-bucket
      - S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack

  localstack:
    container_name: local-aws-cloud
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=0
      - TMPDIR=/tmp/localstack-custom
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack-custom
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
