version: '3.8'

services:
  nginx-service:
    container_name: my-dynamic-web-server
    build:
      context: ./nginx-web  # This context points to the folder containing the Dockerfile
    ports:
      - "8080:80"
    environment:
      # Variables for our entrypoint.sh script
      - S3_BUCKET_NAME=my-dynamic-website-bucket
      - S3_ENDPOINT_URL=http://localstack:4566

      # Variables for the aws-cli running INSIDE the container
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack

  localstack:
    container_name: local-aws-cloud
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"